server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: document-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/documents/**
          filters:
            - StripPrefix=1

        - id: version-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/versions/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
